services:
  php:
    image: php:8.2-fpm
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    links:
      - mysql

  nginx:
    image: nginx:latest
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php

  mysql:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
    - "3306:3306"

volumes:
  mysql_data: {}
