version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/var/www/src
      - ./public:/var/www/public
      - ./config:/var/www/config
      - ./storage:/var/www/storage
      - ./vendor:/var/www/vendor
    ports:
      - "9000:9000"
    networks:
      - app-net
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - app-net
    depends_on:
      - php

  mysql:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  mysql_data: {}
